name: Lunaria

on:
  # Trigger the workflow every time a pull request is opened or synchronized at the target `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  pull_request_target:
    types: [opened, synchronize]
    branches: [main]

# Allow this job to clone the repository and comment on the pull request
permissions:
  contents: read
  pull-requests: write

jobs:
  lunaria-overview:
    name: Generate Lunaria Overview
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Ensure complete Git history
        run: |
          git config --global --add safe.directory $PWD
          if [ -f .git/shallow ]; then
            git fetch --unshallow origin || echo "Already unshallow"
          fi
          git fetch --tags || true
      
      - name: Verify Git state
        run: |
          echo "Current branch: $(git branch --show-current)"
          echo "Commit count: $(git rev-list --count HEAD)"
          git log --oneline -3 || echo "No commits accessible"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm install

      - name: Generate Lunaria Overview
        uses: yanthomasdev/lunaria-action@v0.1.0
        with: 
          token: ${{ secrets.MRROBOTDOTAPP_BOT_TOKEN }}
