name: Lunaria

on:
  # Trigger the workflow every time a pull request is opened or synchronized at the target `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  pull_request_target:
    types: [opened, synchronize]
    branches: [main]

# Allow this job to clone the repository and comment on the pull request
permissions:
  contents: read
  pull-requests: write

jobs:
  lunaria-overview:
    name: Generate Lunaria Overview
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Necessary for Lunaria to work properly
          # Makes the action clone the entire git history
          fetch-depth: 0

      - name: Unshallow repository
        run: |
          if [ -f .git/shallow ]; then
            git fetch --unshallow origin
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm install

      - name: Generate Lunaria Overview
        uses: yanthomasdev/lunaria-action@main
        with: 
          token: ${{ secrets.MRROBOTDOTAPP_BOT_TOKEN }}
